use_frameworks!

platform :ios, '10.0'

target 'ViewHierarchyDebug_Example' do
  pod 'ViewHierarchyDebug', :path => '../'

  target 'ViewHierarchyDebug_Tests' do
    inherit! :search_paths

    
  end
end
