use_frameworks!

platform :ios, '13.0'

target 'ViewHierarchyDebug_Example' do
  pod 'ViewHierarchyDebug', :path => '../'

  target 'ViewHierarchyDebug_Tests' do
    inherit! :search_paths

    pod 'SnapKit'
  end
end
